### ISSUE TITLE
sort of a issue i guess

### ISSUE THREAD

**Issue by CrimsonRed1710** [Adubbz/Tinfoil#3]
any way you could add the command for hactool to get FS.kip1, I'm not very good at using hactool so just wanted to see if you could add it for idiots like me XD

**Comment by TheDgtl** [comment]
hactool --extract --intype=ini1 --extractini1 --ini1dir=./ext/ --keyset keys.txt ini1.bin

You will need your "keys.txt" and an "ini1.bin" from a Hekate backup in the same directory as hactool.
You will end up with FS.kip1 in the "ext" subfolder

**Comment by CrimsonRed1710** [comment]
Also how do i get ini1.bin i would ask someone else but litteraly no one messes around with that stuff that i know of, hactool commands have my brain fried today sorry for pestering you with questions 😥

**Comment by Adubbz** [comment]
The guide has been greatly simplified now. You only need the contents of you SYSTEM:/Contents/registered folder which can be obtained easily from a NAND dump with HacDiskMount.
