### ISSUE TITLE
Title won't disappear after failed installation 

### ISSUE THREAD

**Issue by thomascrha** [Adubbz/Tinfoil#32]
When trying to install a nsp  - I recieve this error - well I received an error I don't think it was this one this was what i got when running the command again.

![2018082119430100-db1426d1dfd034027cecde9c2dd914b8](https://user-images.githubusercontent.com/5226462/44394514-ba00ae00-a57a-11e8-8605-277736d91f9c.jpg)

Which is fine, the application is in development and if it can't install an nsp thats completely understandable. The issue is that the console now has this weird game place holder that has a continuous spinning circle - which can't be deleted by pressing the + button. I've tried rebooting into stock and also using the clear logs feature in hekate (which I knew wasn't going to work but I thought I'd give it a shot) 

![2018082119481500-57b4628d2267231d57e0fc1078c0596d](https://user-images.githubusercontent.com/5226462/44394799-6d69a280-a57b-11e8-85ec-7133194e7a9f.jpg)

Let me know if you needed any more information.

**Comment by Adubbz** [comment]
You should be able to go into data management in settings which will let you delete the icon

**Comment by thomascrha** [comment]
Thank You - you learn something new everyday.
