### ISSUE TITLE
Why only a 4MB buffer?

### ISSUE THREAD

**Issue by kkirby** [Adubbz/Tinfoil#43]
https://github.com/Adubbz/Tinfoil/blob/7066e1ec70abd82ceb714eb64fd221dd33d721bd/source/install/install_nsp.cpp#L102

**Comment by Adubbz** [comment]
Increasing buffer size doesn't inherently guarantee greater performance, the switch itself will still end up writing it to disk in blocks at some point (not sure the exact size it uses though). Furthermore, requiring masses of memory restricts the portability of Tinfoil, especially if I wish to reuse this code in a sysmodule later.

**Comment by kkirby** [comment]
Thanks for the in-depth explanation, I appreciate it.
