### ISSUE TITLE
Warn user tinfoil comes with HIGH ban rIsk on startup. 

### ISSUE THREAD

**Issue by fennectech** [Adubbz/Tinfoil#47]
(See title)

**Comment by aveao** [comment]
Why? Isn't everyone aware that hacking your console will get it banned?

**Comment by Adubbz** [comment]
The same applies to CFW in general. I think such a message just becomes annoying for regular users rather than informing those who don't know.

**Comment by fennectech** [comment]
Ive seen a couple users ask how to install NSPs in discord and when they are told it comes with a high ban risk they almost always back out.
