### ISSUE TITLE
Split file support for fat32 file system?

### ISSUE THREAD

**Issue by Clydefrosch22** [Adubbz/Tinfoil#50]
So we all know that fat32 has a file size limit, meaning installing from one single nsp thats larger than 4gb is impossible. This brings us to an unfortunate impasse with sd card formats, since fat32 has no access to larger games, while exfat corrupts files when using homebrews. While network install is somewhat of a solution, slow install speeds and wonky networks prevent it from being very practical.

There are several ways to split larger files into several smaller ones to abide fat32's filesize limits, both compressed like using winrar or uncompressed like with hjsplit(and probably more).

Since nsp installing over network basically takes the data in small chunks of a large file already, shouldn't this also work if the nsp file is already split up on the sd card, as long as the program knows that say, the five 2gb sized files inside folder X are to be continuously read like one file?

**Comment by Targren** [comment]
Isn't that what "Install Extracted NSP" function is for? As long as the NSP doesn't contain any single files over 4GB (which would prevent them being installed anyway, so it's unlikely) you should be able to install that way.

**Comment by Clydefrosch22** [comment]
well I might be wrong but I was under the impression that extraxted nsps require more space as some nsp inherent compression is lost, which is why language patched games end up bigger much bigger than their original format?

and I saw people mention there are indeed some games that do have larger files even extracted.

**Comment by Targren** [comment]
The extracted files may require more space but no individual file should be over 4GB, since, IIRC, the switch uses Fat32 internally, and so would have the same problem as a Fat32 SD card.

**Comment by Naguz** [comment]
Bayonetta 2 does contain a 13,3GB nca, at least when extracted with nspx. That's well above the 4GiB limit of FAT32. It could be a problem with nspx though, is there a better nsp extractor?

**Comment by Adubbz** [comment]
See https://gbatemp.net/threads/how-to-split-nsps-for-fat32.520157/. The switch natively supports split files in the same way it does for NCAs.

**Comment by Naguz** [comment]
That tool is down already, but a new alternative is available here in case someone else comes looking: https://github.com/AnalogMan151/splitNSP/releases/
