### ISSUE TITLE
Empty title on home screen after installation error

### ISSUE THREAD

**Issue by fernando-freitas-alves** [Adubbz/Tinfoil#52]
Hi there! 

I got this empty title on my home screen after getting an error when trying to install an NSP.

![empty_title](https://user-images.githubusercontent.com/6806898/45504403-27f65a80-b760-11e8-801e-c65d33ff22ab.png)

I can't do anything with this empty title: can't open, can't see options, can't remove, etc.

In the following record, I show that it is not possible to open the title options: https://youtu.be/VPO7VB8HpdU

The error code might be irrelevant because the same happens with different errors. However, I managed to solve when the error was due to no space left (don't remember the error code). All I had to to do was to free some space and try to install again. On the other hand, when I got an error because of the file name (`0x00000202`), after removing accent chars from the NSP filename, it installed but the empty title was still there.

Did anyone have the same problem? Since the home screen titles are somehow managed by the Switch itself and not by the folder content, I have no idea on how to fix it.

**Comment by aveao** [comment]
settings
data management
software
find the title
remove it there

On September 13, 2018 8:29:48 PM GMT+03:00, Fernando Freitas Alves <notifications@github.com> wrote:
>Hi there! 
>
>I got this empty title on my home screen after getting an error when
>trying to install an NSP.
>
>![empty_title](https://user-images.githubusercontent.com/6806898/45504403-27f65a80-b760-11e8-801e-c65d33ff22ab.png)
>
>I can't do anything with this empty title: can't open, can't see
>options, can't remove, etc.
>
>In the following record, I show that it is not possible to open the
>title options: https://youtu.be/VPO7VB8HpdU
>
>The error code might be irrelevant because the same happens with
>different errors. However, I managed to solve when the error was due to
>no space left (don't remember the error code). All I had to to do was
>to free some space and try to install again. On the other hand, when I
>got an error because of the file name (0x00000202), after removing
>accent chars from the NSP filename, it installed but the empty title
>was still there.
>
>Did anyone have the same problem? Since the home screen titles are
>somehow managed by the Switch itself and not by the folder content, I
>have no idea on how to fix it.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Adubbz/Tinfoil/issues/52

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by fernando-freitas-alves** [comment]
Perfect! Thank you. I forgot that possibility.
