### ISSUE TITLE
Broken pipe during network install

### ISSUE THREAD

**Issue by karl0ss** [Adubbz/Tinfoil#53]
Install worked and NSP is ok, but constant errors during network install

`Exception happened during processing of request from ('192.168.4.111', 64906)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------
Shutting down HTTP server...
➜  NSP 192.168.4.111 - - [16/Sep/2018 10:43:47] "GET /AnotherWorld.nsp HTTP/1.1" 206 -
zsh: bad pattern: [16/Sep/2018
➜  NSP ----------------------------------------
zsh: command not found: ----------------------------------------
➜  NSP Exception happened during processing of request from ('192.168.4.111', 31068)
zsh: unknown file attribute:
➜  NSP Traceback (most recent call last):
zsh: no matches found: (most recent call last):
➜  NSP   File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
zsh: command not found: File
➜  NSP     self.process_request(request, client_address)
zsh: missing end of string
➜  NSP   File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
zsh: command not found: File
➜  NSP     self.finish_request(request, client_address)
zsh: missing end of string
➜  NSP   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
zsh: command not found: File
➜  NSP     self.RequestHandlerClass(request, client_address, self)
zsh: missing end of string
➜  NSP   File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
zsh: command not found: File
➜  NSP     self.finish()
function>   File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
➜  NSP     self.wfile.close()
function>   File "/usr/lib/python2.7/socket.py", line 283, in close
➜  NSP     self.flush()
function>   File "/usr/lib/python2.7/socket.py", line 307, in flush
➜  NSP     self._sock.sendall(view[write_offset:write_offset+buffer_size])
zsh: unknown file attribute: v
➜  NSP error: [Errno 32] Broken pipe
zsh: bad pattern: [Errno
➜  NSP ----------------------------------------
zsh: command not found: ----------------------------------------
➜  NSP 192.168.4.111 - - [16/Sep/2018 10:43:47] "GET /AnotherWorld.nsp HTTP/1.1" 206 -
zsh: bad pattern: [16/Sep/2018
➜  NSP ----------------------------------------
zsh: command not found: ----------------------------------------
➜  NSP Exception happened during processing of request from ('192.168.4.111', 63044)
zsh: unknown file attribute:
➜  NSP Traceback (most recent call last):
zsh: no matches found: (most recent call last):
➜  NSP   File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
zsh: command not found: File
➜  NSP     self.process_request(request, client_address)
zsh: missing end of string
➜  NSP   File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
zsh: command not found: File
➜  NSP     self.finish_request(request, client_address)
zsh: missing end of string
➜  NSP   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
zsh: command not found: File
➜  NSP     self.RequestHandlerClass(request, client_address, self)
zsh: missing end of string
➜  NSP   File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
zsh: command not found: File
➜  NSP     self.finish()
function>   File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
➜  NSP     self.wfile.close()
function>   File "/usr/lib/python2.7/socket.py", line 283, in close
➜  NSP     self.flush()
function>   File "/usr/lib/python2.7/socket.py", line 307, in flush
➜  NSP     self._sock.sendall(view[write_offset:write_offset+buffer_size])
zsh: unknown file attribute: v
➜  NSP error: [Errno 32] Broken pipe`

**Comment by Adubbz** [comment]
You're using Python 2.7. It was written for Python 3.

**Comment by karl0ss** [comment]
urgh, yeah, forgot to use python3....

Good it worked anyway :)
