### ISSUE TITLE
Network Install: "URL size 0x1002e296 is too large!"

### ISSUE THREAD

**Issue by LittlestCube** [Adubbz/Tinfoil#60]
I'm attempting to install Minecraft: Story Mode, but the file is too big to just move to the sd card (FAT32), so I tried Network Install and it gave me:

`Accepted client connection`
`Received url buf size: 0x1002e296`
`Failed to perform remote install!`
`OnSelected:165: URL size 0x1002e296 is too large!`

Am I doing something wrong or does file size still matter?

**Comment by Adubbz** [comment]
You need to update Tinfoil. That issue was fixed recently.

**Comment by LittlestCube** [comment]
Ah. My bad.
