### ISSUE TITLE
Relicensing under MIT

### ISSUE THREAD

**Issue by Adubbz** [Adubbz/Tinfoil#62]
Hey folks. Can everyone who contributed please agree to this. @ThatNerdyPikachu @aveao @neonsea @wolfposd @shchmue @facekapow

**Comment by neonsea** [comment]
Aye from me.

**Comment by shchmue** [comment]
sure

**Comment by aveao** [comment]
sure

**Comment by ThatNerdyPikachu** [comment]
sleepy pika says yes

**Comment by wolfposd** [comment]
agree

**Comment by facekapow** [comment]
ok

**Comment by Adubbz** [comment]
Thanks everyone :)
